[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = []

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 3600
